<?php

return [

    'account' => env('PE_ACCOUNT', ''),

    'api_id' => env('PE_API_ID', ''),

    'api_secret_key' => env('PE_API_SECRET_KEY', ''),

    /*
    |--------------------------------------------------------------------------
    | Identifier of your merchant
    |--------------------------------------------------------------------------
    |
    | The identifier of merchant registered in Payeer system on which will be made payment.
    |
    */
    'shop_id' => env('PE_SHOP_ID', ''),

    /*
    |--------------------------------------------------------------------------
    | Payeer Secret key
    |--------------------------------------------------------------------------
    |
    | The identifier of merchant registered in Payeer system on which will be made payment.
    |
    */
    'shop_secret_key' => env('PE_SHOP_SECRET_KEY', ''),

    /*
    |--------------------------------------------------------------------------
    | Payeer Additional Key
    |--------------------------------------------------------------------------
    |
    | The identifier of merchant registered in Payeer system on which will be made payment.
    |
    */
    'shop_additional_key' => env('PE_SHOP_ADDITIONAL_KEY', ''),

    /*
    |--------------------------------------------------------------------------
    | Electronic signature (Optional)
    |--------------------------------------------------------------------------
    |
    | A security signature used to check the cohesiveness of the information obtained
    | and directly identify the sender.
    |
    */
    'shop_sign' => env('PE_SHOP_SIGN', ''),

    /*
    |--------------------------------------------------------------------------
    | Payment currency
    |--------------------------------------------------------------------------
    |
    | The currency used in the payment
	|
	| Potential currencies: USD, EUR, RUB
    |
    */
    'currency' => env('PE_CURRENCY', 'USD'),

    /*
    |--------------------------------------------------------------------------
    | Payment description
    |--------------------------------------------------------------------------
    |
    | A description of the product or service. Generated by the seller. This line is added to the payment designation.
    |
    */
    'description' => env('PE_DESCRIPTION', null),
];
