<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateReferalTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('referal', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('level');
            $table->string('name', 200)->nullable();
            $table->integer('from_value');
            $table->integer('to_value');
            $table->double('percent', 10, 2)->nullable();
            $table->double('percent_daily', 10, 2)->nullable();
            $table->double('percent_weekly', 10, 2)->nullable();
            $table->double('percent_monthly', 10, 2)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('referal');
    }
}
