<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePendingDepositsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pending_deposits', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedinteger('ec')->nullable();
            $table->text('fields')->nullable();
            $table->unsignedinteger('user_id');
            $table->float('amount', 10, 5)->default(0.00000);
            $table->unsignedinteger('type_id');
            $table->dateTime('date')->default('2017-01-01 00:00:00');
            $table->enum('status', ['new', 'problem', 'processed'])->default('new');
            $table->double('compound', 10, 5)->default(0.00000);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pending_deposits');
    }
}
