<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 200)->nullable();
            $table->string('username', 20)->nullable();
            $table->string('password');
            $table->dateTime('date_register')->nullable();
            $table->string('email', 200)->unique()->nullable();
            $table->enum('status', ['on', 'off', 'suspended'])->nullable();
            $table->text('came_from');
            $table->bigInteger('ref');
            $table->float('deposit_total', 10, 2)->default(0.00);
            $table->string('confirm_string', 200);
            $table->string('ip_reg', 15);
            $table->dateTime('last_access_time')->default('2017-01-01 00:00:00');
            $table->string('last_access_ip', 15);
            $table->string('stat_password', 200);
            $table->integer('auto_withdraw')->default(1);
            $table->integer('user_auto_pay_earning');
            $table->integer('admin_auto_pay_earning');
            $table->string('pswd', 50);
            $table->string('hid', 50);
            $table->string('question', 50);
            $table->string('answer', 50);
            $table->dateTime('l_e_t')->default('2004-01-01 00:00:00');
            $table->string('activation_code', 50);
            $table->unsignedTinyInteger('bf_counter');
            $table->string('address', 255)->nullable();
            $table->string('city', 255)->nullable();
            $table->string('state', 255)->nullable();
            $table->string('zip', 255)->nullable();
            $table->string('country', 255)->nullable();
            $table->string('transaction_code', 255)->nullable();
            $table->string('payeer_account', 200);
            $table->string('perfectmoney_account', 200);
            $table->string('bitcoin_account', 200);
            $table->bigInteger('intgold_account');
            $table->bigInteger('evocash_account');
            $table->bigInteger('egold_account');
            $table->string('stormpay_account', 200);
            $table->string('ebullion_account', 200);
            $table->string('paypal_account', 200);
            $table->string('goldmoney_account', 200);
            $table->bigInteger('eeecurrency_account');
            $table->bigInteger('pecunix_account');
            $table->text('ac');
            $table->tinyInteger('is_test')->nullable();
            $table->string('explicit_password', 50)->nullable();
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
