<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export.
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateWiresTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('wires', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id');
            $table->string('pname', 250);
            $table->string('paddress', 250);
            $table->string('pzip', 250);
            $table->string('pcity', 250);
            $table->string('pstate', 250);
            $table->string('pcountry', 250);
            $table->string('bname', 250);
            $table->string('baddress', 250);
            $table->string('bzip', 250);
            $table->string('bcity', 250);
            $table->string('bstate', 250);
            $table->string('bcountry', 250);
            $table->string('baccount', 250);
            $table->string('biban', 250);
            $table->string('bswift', 250);
            $table->float('amount', 10, 5)->nullable();
            $table->integer('type_id')->nullable();
            $table->dateTime('wire_date');
            $table->float('compound', 10, 5)->nullable();
            $table->enum('status', ['new', 'problem', 'processed'])->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('wires');
    }
}
